### ISSUE TITLE
TCGA_PHATE_with_TissueTypeComBatCorrection.R

### ISSUE THREAD

**Issue by DWGFAKER** [secrierlab/CancerDormancy#1]
Hi, thank you for sharing your good work, I am now learning it. In part TCGA_PHATE_with_TissueTypeComBatCorrection.R, TCGA_combat_tumor_type_correction.txt is an example dataframe, so how to get all  combat example dataframe.

**Comment by annawiecek** [comment]
Hi DWGFAKER, thank you for your comment! To obtain the full expression data with correction for cancer type first download the expression data as described by the "TCGA_Expression_CNV_DataDownload.R" script and then apply the ComBat function from the sva R package. When using the ComBat function specify that the TCGA cancer type annotations should be treated as a batches. There are more details on this in the methods section of the associated preprint. Hopefully this helps.
